language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
addons:
  sonarcloud:
    organization: westfr-github
    token:
      secure: VQBXa6CBDoid1mxeimoJpa0sDwyDm6qZh6USAeGOBjxIrTDfxfgTGNExID4S86q5vroCURv+D44oTZv3mpXKnpC1A7vwmL4WO0lSRUVG9gC5dDNEdDMn1+dOvlw0VPQ+UGbPD68t0Z6Ogi5kedAoge+lITe/Cz78gLaF0ic0qmZocv/TK5+4w1W7gfMBS4s6cBE29IK6RZG6Z6Wwc1q5DJpVh/OOUoJGiPKHvsSyQ9xeUwAfP7W5reAgtt1UzXpUcm2AXUaqYxSUkRsQrwJot33630bNRvV8KI+Hbb8E1qs/zQPt6DEmlbFy/uhxt0ByEr1l+ri0KwRs6eU0Ywzg8yXggUS4fvpxAluh3okL+l21t6Xd3ePzHoMyw3MbXE5JzEkmt7bvTE3gvka3q0Lo6eYwW37HY+wQYO10g07F2nxmrrL6QKeBvEO6vdG3dLK0HiW3P3ZpAQx+GAKq4z9WsHuVvT/F+K7XZR6q3ln1tMUcZy7siDhUolGL8nsYovp23qgT1dQhnsTZ9np0To2UQQ1ONx/MRCK9Cdy2w2T3e1IXfVySBYwkcQxB/ZDvLQd/yWBwJ3l8yvznLJwDUaOSNx1uls+nfbJPKuFkqmU+JJsKF/wQURMPjGFCB+OULg6TI8j69NRw8BQPOgCr2jvafemL3AWVQGezEOL6tkRFC4w=
# command to run tests
script:
  - pytest --cov .
  - sonar-scanner
  - coveralls        
